In [1]:
import bigfile
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from mpl_toolkits.mplot3d import Axes3D
from nbodykit.lab import BigFileCatalog
from scipy.spatial import distance

# Import class to analyze MP_Gadget run snapshots
from dm_snapshot_analysis import SnapshotData

In [2]:
# Snapshot imports to obtain DM particle attributes
snapshot000 = '/home/aschann/MP-Gadget/DM_Halos_March10/output/PART_000'
snapshot001 = '/home/aschann/MP-Gadget/DM_Halos_March10/output/PART_001'
snapshot002 = '/home/aschann/MP-Gadget/DM_Halos_March10/output/PART_002'
snapshot003 = '/home/aschann/MP-Gadget/DM_Halos_March10/output/PART_003'
snapshot004 = '/home/aschann/MP-Gadget/DM_Halos_March10/output/PART_004'
snapshot005 = '/home/aschann/MP-Gadget/DM_Halos_March10/output/PART_005'
snapshot006 = '/home/aschann/MP-Gadget/DM_Halos_March10/output/PART_006'

# Import class to obtain data from snapshot 
snap0 = SnapshotData(snapshot000)
snap1 = SnapshotData(snapshot001)
snap2 = SnapshotData(snapshot002)
snap3 = SnapshotData(snapshot003)
snap4 = SnapshotData(snapshot004)
snap5 = SnapshotData(snapshot005)
snap6 = SnapshotData(snapshot006)

/home/aschann/miniconda/envs/test/lib/python3.6/site-packages/bigfile/__init__.py:358: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  return pyxbigfile.Dataset.__init__(self, file, dtype=dtype, size=size)


In [3]:
# Get total angular momentum of each snapshot and system
L0 = snap0.calculate_system_angular_momentum()
L1 = snap1.calculate_system_angular_momentum()
L2 = snap2.calculate_system_angular_momentum()
L3 = snap3.calculate_system_angular_momentum()
L4 = snap4.calculate_system_angular_momentum()
L5 = snap5.calculate_system_angular_momentum()
L6 = snap6.calculate_system_angular_momentum()

In [4]:
print(L0)
print(L1)
print(L2)
print(L3)
print(L4)
print(L5)
print(L6)

[[ 13657970.22454089  -4449384.79542856  -9208725.69451371]
 [ 10983495.4705533   -3241510.03882403  -7690723.49426684]
 [ 13919957.89007424  -8737510.25761675  -5264076.38763057]
 ...
 [ 12293846.92033028 -10209742.02198309  -2150875.30731083]
 [ 13738302.92529139  -6919544.82255485  -6817418.11063284]
 [ 12901128.99236584  -8574232.14498132  -4396246.43753783]]
[[-50540734.39390761  23094363.1975356   73606390.871387  ]
 [-58247566.01088781  18604145.91028506  77125138.45328218]
 [-58051800.74283715  34713972.58450476  92355082.93742245]
 ...
 [ 31082053.79820458 -50543635.49907454  81977475.97228155]
 [ 31725990.71094052 -18967520.1966458  -12955123.11761351]
 [ 36305083.98732345 -37830529.48116605  74178369.63823043]]
[[-49592529.47167904  28704726.38564221  78339922.03549431]
 [-48567035.06813671  18379336.44848829 -30227828.86655396]
 [-56742800.60940637  25781329.22625288 -30580763.39814315]
 ...
 [ 39436674.41525432 -23342171.37391786 -16340056.98536494]
 [ 34465589.07609642 -1

In [27]:
# Difference between the angular momentum of the two snapshots
L6 - L0

array([ 1.68695763e+11,  6.96792496e+10, -3.13320294e+11])

In [24]:
# RMS of positions/radii of first and last snapshot
print(snap0.calculate_rms(type=1))
print(snap6.calculate_rms(type=1))

249.98356159114905
248.93999382216276


In [25]:
# RMS of velocities for first and last snapshot
print(snap0.calculate_rms(type=0))
print(snap6.calculate_rms(type=0))

96.99431
586.1904


In [5]:
v0 = snap0.load_velocities()

In [6]:
print(v0)

None


In [6]:
# Import data manually/separately to look at 'new' parameters
data = BigFileCatalog(snapshot000, dataset='1/', header='Header')

# Get data without "lazy" array retrieval (yet)
pos = data['Position'].compute() / 1000
group_ids = data['GroupID'].compute()
v0 = data['Velocity'].compute()

In [70]:
v0

array([[ 22.63697 , -57.42381 ,  61.323414],
       [ 22.3273  , -48.140186,  50.512665],
       [-10.405549, -55.466026,  68.42081 ],
       ...,
       [-24.50619 , -42.92058 ,  71.414986],
       [  8.012158, -55.06678 ,  71.98856 ],
       [  6.408032, -31.817816,  84.79968 ]], dtype=float32)

In [71]:
np.shape(v0)

(2097152, 3)

In [72]:
np.sum(v0[:,1])

-3.6953125

In [73]:
np.shape(pos)

(2097152, 3)

In [74]:
(np.mean(pos[:,0]))

250.3795623759472

In [75]:
np.mean(pos[:,1])

249.32694434898036

In [76]:
np.mean(pos[:,2])

249.36938285834762

In [77]:
v0.mean(axis=0)

array([ 7.249135e-05, -1.237519e-05,  6.698906e-05], dtype=float32)

In [78]:
np.cross(pos,v0)

array([[ 58909.83938376, -19192.28579718, -39717.85488575],
       [ 49138.77505107, -13982.68867469, -35045.97062853],
       [ 61726.85661162, -39372.22713416, -22529.97621638],
       ...,
       [ 56831.80884696, -47768.31062467,  -9206.92778851],
       [ 63096.68534104, -31769.55621509, -31324.25057441],
       [ 57729.22492049, -38914.58738617, -18963.60741208]])

In [79]:
_.shape

(2097152, 3)

In [80]:
_.__len__()

2

In [81]:
pos[0], v0[0]

(array([496.15737722, 495.94129156, 496.25802933]),
 array([ 22.63697 , -57.42381 ,  61.323414], dtype=float32))

In [82]:
np.cross( pos[0], v0[0])

array([ 58909.83938376, -19192.28579718, -39717.85488575])

In [83]:
4.93686264e+02 * 1024.8463 - (4.92452731e+02 *-196.73647)

602835.9529600227

In [12]:
xcm = np.mean(pos, axis = 0 ) 
vcm = v0.mean( axis = 0 )

R = pos - xcm 
V = v0 - vcm 

In [13]:
R.mean( axis = 0 )

array([-1.65720712e-11,  1.20745232e-11, -4.90409062e-12])

In [18]:
L = np.cross ( R, V )
L

array([[ 29300.50040814,  -9483.12466074, -19696.07932927],
       [ 24539.89810684,  -6903.09558687, -17425.83361028],
       [ 30836.1571238 , -19646.23086222, -11236.77955776],
       ...,
       [ 28323.02970761, -23776.36493305,  -4570.52358772],
       [ 31416.00781671, -15743.07891481, -15538.98633491],
       [ 28651.97036673, -19280.44767601,  -9399.36090647]])

In [19]:
L.shape

(2097152, 3)

In [87]:
L.sum(axis = 0 ) 

array([ 28494522.04695189,   8389086.77882007, -39794295.00048253])

In [88]:
L.max(axis = 0 ) 

array([70388.4086699 , 69159.75399219, 59726.55974818])

In [5]:
### March 31st pipeline refactor
def calculate_L(positions, velocities):
    # Calculates center of mass for positons and velocity
    pos_com = np.mean(positions, axis = 0 ) 
    vel_com = velocities.mean( axis = 0 )

    # Calculates relative positons and relative velocities
    R = pos - pos_com 
    V = velocities - vel_com 
    
    # 
    L = np.cross(R, V)
    return L

In [8]:
calculate_L(pos, v)

array([[ 29300.50040814,  -9483.12466074, -19696.07932927],
       [ 24539.89810684,  -6903.09558687, -17425.83361028],
       [ 30836.1571238 , -19646.23086222, -11236.77955776],
       ...,
       [ 28323.02970761, -23776.36493305,  -4570.52358772],
       [ 31416.00781671, -15743.07891481, -15538.98633491],
       [ 28651.97036673, -19280.44767601,  -9399.36090647]])

In [11]:
# Check prof Boily's method against original 
print(np.sum(L6, axis=0) )

L6_2 = snap6.OLD_calculate_system_angular_momentum()
print(L6_2) 

# Different?

[ 1.62788666e+11  8.92650089e+11 -1.13174081e+12]
[ 1.81960742e+11  7.35845959e+10 -3.31845626e+11]


In [9]:
pos[0]

array([496.15737722, 495.94129156, 496.25802933])